$:
  vscode:
    - docker:
        image: docker.cnb.cool/examples/language/python-3:3.10
      runner:
        tags: cnb:arch:amd64 # arm64:v8 amd64
        cpus: 8
      services:
        - vscode
        - docker
      volumes:
        - /root/.cache/pip:copy-on-write
        - /root/.local/share/uv:copy-on-write
      stages:
        - name: Install dependencies
          script: |
            pip install uv
            uv sync
        - name: Run dev server
          script: uv run python main.py